server:
  port: 8080

spring:
  application:
    name: enterprise-auth-platform
  main:
    banner-mode: "off"
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/enterprise_auth_platform?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  boot:
    admin:
      client:
        enabled: false
  flyway:
    enabled: false
  jackson:
    time-zone: Asia/Shanghai
    default-property-inclusion: non_null

management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    db:
      enabled: true

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

knife4j:
  enable: true

app:
  authorization-server:
    issuer: http://127.0.0.1:8080
  frontend:
    allowed-origins:
      - http://127.0.0.1:5173
      - http://localhost:5173
    public-client-id: eap-frontend-spa
    public-client-name: 前端管理台
    redirect-uris:
      - http://127.0.0.1:5173/auth/callback
      - http://localhost:5173/auth/callback
    scopes:
      - openid
      - profile
      - api.read
      - api.write
  security:
    jwt-secret: "change-me-to-a-32-char-secret-key-for-prod"
    access-token-ttl: 30m
    refresh-token-ttl: 7d
    captcha-ttl: 5m
    expose-captcha-answer: true
    redis:
      session-enabled: false
      captcha-enabled: false
      redisson-enabled: false
      key-prefix: "eap:auth:"
  tenant:
    header-name: X-Tenant-Id
    platform-tenant-id: platform
    mybatis-tenant-enabled: true
    mybatis-ignore-tables:
      - flyway_schema_history
  persistence:
    database-enabled: true
  features:
    gateway-enabled: false
    nacos-enabled: false
    mq-enabled: false
    seata-enabled: false
    job-enabled: false
    loki-enabled: false

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger - %msg%n"
