package com.enterprise.auth.platform.modules.codegen.domain.render;

import com.enterprise.auth.platform.modules.codegen.domain.CodegenTypeMappings;
import com.enterprise.auth.platform.modules.codegen.domain.model.RenderContext;

/**
 * Vue 页面级模板渲染纯逻辑：列表页 index.vue 与弹窗表单 form.vue。
 */
class VueViewRenderer {

    private final VueSnippetRenderer snippets;

    VueViewRenderer(VueSnippetRenderer snippets) {
        this.snippets = snippets;
    }

    /**
     * 旧版单文件视图模板。迁移自原 CodegenApplicationService#renderView，
     * 原实现中即已无调用方（疑似遗留代码），为保持行为一致原样保留。
     */
    String renderView(RenderContext model) {
        return "<template>\n"
                + "  <div class=\"panel-stack\">\n"
                + "    <section class=\"dashboard-panel\">\n"
                + "      <div class=\"panel-head\">\n"
                + "        <div>\n"
                + "          <span class=\"eyebrow\">Generated CRUD</span>\n"
                + "          <h3>" + RenderSupport.escapeVue(model.title()) + "</h3>\n"
                + "        </div>\n"
                + "        <div class=\"panel-actions\">\n"
                + "          <el-button v-permission=\"'" + model.moduleName() + ":page'\" :loading=\"loading\" @click=\"load\">刷新</el-button>\n"
                + "          <el-button v-permission=\"'" + model.moduleName() + ":add'\" type=\"primary\" @click=\"openForm()\">新增</el-button>\n"
                + "        </div>\n"
                + "      </div>\n\n"
                + "      <el-form :inline=\"true\" :model=\"query\" class=\"codegen-search\">\n"
                + snippets.renderVueSearchItems(model)
                + "        <el-form-item>\n"
                + "          <el-button type=\"primary\" @click=\"handleSearch\">查询</el-button>\n"
                + "          <el-button @click=\"resetSearch\">重置</el-button>\n"
                + "        </el-form-item>\n"
                + "      </el-form>\n\n"
                + "      <el-table v-loading=\"loading\" :data=\"records\" stripe>\n"
                + snippets.renderVueColumns(model)
                + "        <el-table-column fixed=\"right\" label=\"操作\" width=\"180\">\n"
                + "          <template #default=\"{ row }\">\n"
                + "            <el-button v-permission=\"'" + model.moduleName() + ":get'\" link type=\"primary\" @click=\"openDetail(row)\">详情</el-button>\n"
                + "            <el-button v-permission=\"'" + model.moduleName() + ":edit'\" link type=\"primary\" @click=\"openForm(row)\">编辑</el-button>\n"
                + "            <el-button v-permission=\"'" + model.moduleName() + ":del'\" link type=\"danger\" @click=\"remove(row)\">删除</el-button>\n"
                + "          </template>\n"
                + "        </el-table-column>\n"
                + "        <template #empty><el-empty description=\"暂无数据\" /></template>\n"
                + "      </el-table>\n\n"
                + "      <div class=\"pagination-wrap\">\n"
                + "        <el-pagination\n"
                + "          v-model:current-page=\"page\"\n"
                + "          v-model:page-size=\"size\"\n"
                + "          :page-sizes=\"[10, 20, 50, 100]\"\n"
                + "          layout=\"total, sizes, prev, pager, next\"\n"
                + "          :total=\"total\"\n"
                + "          @size-change=\"handleSizeChange\"\n"
                + "          @current-change=\"handleCurrentChange\"\n"
                + "        />\n"
                + "      </div>\n"
                + "    </section>\n\n"
                + "    <el-drawer v-model=\"detailVisible\" title=\"详情\" size=\"560px\">\n"
                + "      <el-descriptions v-if=\"detailItem\" :column=\"1\" border>\n"
                + snippets.renderVueDescriptions(model)
                + "      </el-descriptions>\n"
                + "    </el-drawer>\n\n"
                + "    <el-dialog v-model=\"formVisible\" :title=\"editingId === null ? '新增' : '编辑'\" width=\"560px\">\n"
                + "      <el-form ref=\"formRef\" label-position=\"top\" :model=\"form\" :rules=\"editingId === null ? createRules : updateRules\">\n"
                + snippets.renderVueFormItems(model)
                + "      </el-form>\n"
                + "      <template #footer>\n"
                + "        <el-button @click=\"formVisible = false\">取消</el-button>\n"
                + "        <el-button v-if=\"editingId === null\" v-permission=\"'" + model.moduleName() + ":add'\" type=\"primary\" @click=\"submit\">保存</el-button>\n"
                + "        <el-button v-else v-permission=\"'" + model.moduleName() + ":edit'\" type=\"primary\" @click=\"submit\">保存</el-button>\n"
                + "      </template>\n"
                + "    </el-dialog>\n"
                + "  </div>\n"
                + "</template>\n\n"
                + "<script setup lang=\"ts\">\n"
                + "import { reactive, ref, toRefs } from 'vue'\n"
                + "import { ElMessage, ElMessageBox } from 'element-plus'\n"
                + "import type { FormInstance, FormRules } from 'element-plus'\n"
                + "import { create" + model.className() + ", delete" + model.className() + ", query" + model.className() + "Page, update" + model.className() + " } from '#/api/" + model.kebabName() + "'\n"
                + "import type { " + model.className() + "CreateRequest, " + model.className() + "QueryParams, " + model.className() + "UpdateRequest, " + model.className() + "View } from '#/types/" + model.moduleName() + "'\n\n"
                + "const loading = ref(false)\n"
                + "const formVisible = ref(false)\n"
                + "const detailVisible = ref(false)\n"
                + "const records = ref<" + model.className() + "View[]>([])\n"
                + "const detailItem = ref<" + model.className() + "View | null>(null)\n"
                + "const editingId = ref<" + CodegenTypeMappings.tsScalarType(model.primaryKeyJavaType()) + " | null>(null)\n"
                + "const query = reactive<" + model.className() + "QueryParams>(" + RenderSupport.renderTsInitialQuery(model) + ")\n"
                + "const page = ref(1)\n"
                + "const size = ref(20)\n"
                + "const total = ref(0)\n"
                + "const formRef = ref<FormInstance>()\n\n"
                + "const form = reactive<" + model.className() + "CreateRequest & " + model.className() + "UpdateRequest>(" + RenderSupport.renderTsInitialForm(model) + ")\n\n"
                + "const createRules = reactive<FormRules>(" + RenderSupport.renderTsRules(model.insertColumns()) + ")\n"
                + "const updateRules = reactive<FormRules>(" + RenderSupport.renderTsRules(model.editColumns()) + ")\n\n"
                + "void load()\n\n"
                + "async function load() {\n"
                + "  loading.value = true\n"
                + "  try {\n"
                + "    const result = await query" + model.className() + "Page({\n"
                + "      ...query,\n"
                + "      page: page.value,\n"
                + "      size: size.value,\n"
                + "    })\n"
                + "    records.value = result.records\n"
                + "    total.value = result.total\n"
                + "  } finally {\n"
                + "    loading.value = false\n"
                + "  }\n"
                + "}\n\n"
                + "function handleSearch() {\n"
                + "  page.value = 1\n"
                + "  void load()\n"
                + "}\n\n"
                + "function resetSearch() {\n"
                + "  Object.assign(query, " + RenderSupport.renderTsInitialQuery(model) + ")\n"
                + "  page.value = 1\n"
                + "  void load()\n"
                + "}\n\n"
                + "function handleSizeChange(value: number) {\n"
                + "  size.value = value\n"
                + "  page.value = 1\n"
                + "  void load()\n"
                + "}\n\n"
                + "function handleCurrentChange(value: number) {\n"
                + "  page.value = value\n"
                + "  void load()\n"
                + "}\n\n"
                + "function openDetail(row: " + model.className() + "View) {\n"
                + "  detailItem.value = row\n"
                + "  detailVisible.value = true\n"
                + "}\n\n"
                + "function openForm(row?: " + model.className() + "View) {\n"
                + "  editingId.value = row?." + model.primaryKeyField() + " ?? null\n"
                + "  Object.assign(form, toForm(row))\n"
                + "  formVisible.value = true\n"
                + "}\n\n"
                + "async function submit() {\n"
                + "  if (!formRef.value) {\n"
                + "    return\n"
                + "  }\n"
                + "  await formRef.value.validate()\n"
                + "  if (editingId.value === null) {\n"
                + "    await create" + model.className() + "(toCreatePayload())\n"
                + "    ElMessage.success('已创建')\n"
                + "  } else {\n"
                + "    await update" + model.className() + "(editingId.value, toUpdatePayload())\n"
                + "    ElMessage.success('已更新')\n"
                + "  }\n"
                + "  formVisible.value = false\n"
                + "  await load()\n"
                + "}\n\n"
                + "async function remove(row: " + model.className() + "View) {\n"
                + "  await ElMessageBox.confirm('删除后不可恢复，是否继续？', '删除确认', { type: 'warning' })\n"
                + "  await delete" + model.className() + "(row." + model.primaryKeyField() + ")\n"
                + "  ElMessage.success('已删除')\n"
                + "  await load()\n"
                + "}\n\n"
                + "function toForm(row?: " + model.className() + "View): " + model.className() + "CreateRequest & " + model.className() + "UpdateRequest {\n"
                + RenderSupport.renderTsToForm(model)
                + "}\n\n"
                + "function toCreatePayload(): " + model.className() + "CreateRequest {\n"
                + RenderSupport.renderTsPayload(model.insertColumns())
                + "}\n\n"
                + "function toUpdatePayload(): " + model.className() + "UpdateRequest {\n"
                + RenderSupport.renderTsPayload(model.editColumns())
                + "}\n"
                + "</script>\n";
    }

    String renderIndexView(RenderContext model) {
        String permissionModule = model.moduleName();
        return "<template>\n"
                + "  <div class=\"hx-layout-container\">\n"
                + "    <div class=\"hx-layout-container-auto hx-layout-container-view\">\n"
                + "      <div class=\"hx-table-toolbar\" style=\"display: flex; gap: 8px; margin-bottom: 12px\">\n"
                + "        <el-button v-access:code=\"'" + permissionModule + ":add'\" :icon=\"Plus\" type=\"primary\" @click=\"openForm()\">新增</el-button>\n"
                + "        <el-button :icon=\"Refresh\" @click=\"load\">刷新</el-button>\n"
                + "      </div>\n"
                + "      <el-form :inline=\"true\" :model=\"query\" class=\"codegen-search\">\n"
                + snippets.renderVueSearchItems(model)
                + "        <el-form-item>\n"
                + "          <el-button type=\"primary\" @click=\"handleSearch\">查询</el-button>\n"
                + "          <el-button @click=\"resetSearch\">重置</el-button>\n"
                + "        </el-form-item>\n"
                + "      </el-form>\n"
                + "      <el-table v-loading=\"loading\" :data=\"records\" stripe>\n"
                + snippets.renderVueColumns(model)
                + "        <el-table-column align=\"center\" fixed=\"right\" label=\"操作\" width=\"180\">\n"
                + "          <template #default=\"{ row }\">\n"
                + "            <el-button v-access:code=\"'" + permissionModule + ":get'\" link type=\"primary\" @click=\"openDetail(row)\">详情</el-button>\n"
                + "            <el-button v-access:code=\"'" + permissionModule + ":edit'\" link type=\"primary\" @click=\"openForm(row)\">修改</el-button>\n"
                + "            <el-button v-access:code=\"'" + permissionModule + ":del'\" link type=\"danger\" @click=\"remove(row)\">删除</el-button>\n"
                + "          </template>\n"
                + "        </el-table-column>\n"
                + "        <template #empty><el-empty description=\"暂无数据\" /></template>\n"
                + "      </el-table>\n"
                + "      <div class=\"pagination-wrap\">\n"
                + "        <el-pagination\n"
                + "          v-model:current-page=\"page\"\n"
                + "          v-model:page-size=\"size\"\n"
                + "          :page-sizes=\"[10, 20, 50, 100]\"\n"
                + "          layout=\"total, sizes, prev, pager, next\"\n"
                + "          :total=\"total\"\n"
                + "          @size-change=\"handleSizeChange\"\n"
                + "          @current-change=\"handleCurrentChange\"\n"
                + "        />\n"
                + "      </div>\n"
                + "    </div>\n"
                + "  </div>\n"
                + "  <el-drawer v-model=\"detailVisible\" title=\"详情\" size=\"560px\">\n"
                + "    <el-descriptions v-if=\"detailItem\" :column=\"1\" border>\n"
                + snippets.renderVueDescriptions(model)
                + "    </el-descriptions>\n"
                + "  </el-drawer>\n"
                + "  <Form ref=\"formRef\" @init-page=\"load\" />\n"
                + "</template>\n\n"
                + "<script setup lang=\"ts\">\n"
                + "import { reactive, ref } from 'vue'\n"
                + "import { ElMessage, ElMessageBox } from 'element-plus'\n"
                + "import { Refresh, Plus } from '@element-plus/icons-vue'\n"
                + "import { query" + model.className() + "Page, delete" + model.className() + " } from '#/api/" + model.kebabName() + "'\n"
                + "import type { " + model.className() + "QueryParams, " + model.className() + "View } from '#/types/" + model.moduleName() + "'\n"
                + "import Form from './form.vue'\n\n"
                + "const loading = ref(false)\n"
                + "const detailVisible = ref(false)\n"
                + "const records = ref<" + model.className() + "View[]>([])\n"
                + "const detailItem = ref<" + model.className() + "View | null>(null)\n"
                + "const query = reactive<" + model.className() + "QueryParams>(" + RenderSupport.renderTsInitialQuery(model) + ")\n"
                + "const page = ref(1)\n"
                + "const size = ref(20)\n"
                + "const total = ref(0)\n"
                + "const formRef = ref<InstanceType<typeof Form>>()\n\n"
                + "void load()\n\n"
                + "async function load() {\n"
                + "  loading.value = true\n"
                + "  try {\n"
                + "    const result = await query" + model.className() + "Page({\n"
                + "      ...query,\n"
                + "      page: page.value,\n"
                + "      size: size.value,\n"
                + "    })\n"
                + "    records.value = result.records\n"
                + "    total.value = result.total\n"
                + "  } finally {\n"
                + "    loading.value = false\n"
                + "  }\n"
                + "}\n\n"
                + "function handleSearch() {\n"
                + "  page.value = 1\n"
                + "  void load()\n"
                + "}\n\n"
                + "function resetSearch() {\n"
                + "  Object.assign(query, " + RenderSupport.renderTsInitialQuery(model) + ")\n"
                + "  page.value = 1\n"
                + "  void load()\n"
                + "}\n\n"
                + "function handleSizeChange(value: number) {\n"
                + "  size.value = value\n"
                + "  page.value = 1\n"
                + "  void load()\n"
                + "}\n\n"
                + "function handleCurrentChange(value: number) {\n"
                + "  page.value = value\n"
                + "  void load()\n"
                + "}\n\n"
                + "function openDetail(row: " + model.className() + "View) {\n"
                + "  detailItem.value = row\n"
                + "  detailVisible.value = true\n"
                + "}\n\n"
                + "function openForm(row?: " + model.className() + "View) {\n"
                + "  formRef.value?.initForm(row)\n"
                + "}\n\n"
                + "async function remove(row: " + model.className() + "View) {\n"
                + "  await ElMessageBox.confirm('删除后不可恢复，是否继续？', '删除确认', { type: 'warning' })\n"
                + "  await delete" + model.className() + "(row." + model.primaryKeyField() + ")\n"
                + "  ElMessage.success('已删除')\n"
                + "  await load()\n"
                + "}\n"
                + "</script>\n";
    }

    String renderFormView(RenderContext model) {
        return "<template>\n"
                + "  <el-dialog v-model=\"dialog\" :before-close=\"handleClose\" :title=\"editingId ? '编辑' : '新增'\" width=\"640px\">\n"
                + "    <el-form ref=\"formRef\" label-width=\"120px\" :model=\"form\" :rules=\"rules\">\n"
                + snippets.renderVueFormItems(model)
                + "    </el-form>\n"
                + "    <template #footer>\n"
                + "      <span class=\"dialog-footer\">\n"
                + "        <el-button @click=\"handleClose\">关 闭</el-button>\n"
                + "        <el-button :loading=\"loading\" type=\"primary\" @click=\"submitForm(formRef)\">确 认</el-button>\n"
                + "      </span>\n"
                + "    </template>\n"
                + "  </el-dialog>\n"
                + "</template>\n\n"
                + "<script setup lang=\"ts\">\n"
                + "import type { FormInstance, FormRules } from 'element-plus'\n"
                + "import { reactive, ref, toRefs } from 'vue'\n"
                + "import { ElMessage } from 'element-plus'\n"
                + "import { create" + model.className() + ", update" + model.className() + " } from '#/api/" + model.kebabName() + "'\n"
                + "import type { " + model.className() + "CreateRequest, " + model.className() + "UpdateRequest, " + model.className() + "View } from '#/types/" + model.moduleName() + "'\n\n"
                + "const emit = defineEmits(['initPage'])\n\n"
                + "function defaultForm(): " + model.className() + "CreateRequest & " + model.className() + "UpdateRequest {\n"
                + "  return " + RenderSupport.renderTsInitialForm(model) + "\n"
                + "}\n\n"
                + "const state = reactive({\n"
                + "  form: defaultForm(),\n"
                + "  rules: " + RenderSupport.renderTsRules(model.insertColumns()) + " as FormRules,\n"
                + "})\n"
                + "const { form, rules } = toRefs(state)\n"
                + "const dialog = ref(false)\n"
                + "const loading = ref(false)\n"
                + "const formRef = ref()\n"
                + "const editingId = ref<" + CodegenTypeMappings.tsScalarType(model.primaryKeyJavaType()) + " | null>(null)\n\n"
                + "const initForm = (row?: " + model.className() + "View) => {\n"
                + "  state.form = defaultForm()\n"
                + "  if (row && row." + model.primaryKeyField() + ") {\n"
                + "    editingId.value = row." + model.primaryKeyField() + "\n"
                + "    Object.assign(state.form, toForm(row))\n"
                + "  } else {\n"
                + "    editingId.value = null\n"
                + "  }\n"
                + "  dialog.value = true\n"
                + "}\n\n"
                + "defineExpose({ initForm })\n\n"
                + "const handleClose = () => {\n"
                + "  dialog.value = false\n"
                + "  formRef.value?.resetFields()\n"
                + "}\n\n"
                + "function buildPayload() {\n"
                + "  return {\n"
                + "    ...state.form,\n"
                + "  }\n"
                + "}\n\n"
                + "const submitForm = async (formEl: FormInstance | undefined) => {\n"
                + "  if (!formEl) return\n"
                + "  await formEl.validate(async (valid) => {\n"
                + "    if (!valid) return\n"
                + "    loading.value = true\n"
                + "    const payload = buildPayload()\n"
                + "    if (editingId.value === null) {\n"
                + "      await create" + model.className() + "(payload)\n"
                + "      ElMessage.success('新增成功')\n"
                + "    } else {\n"
                + "      await update" + model.className() + "(editingId.value, payload)\n"
                + "      ElMessage.success('修改成功')\n"
                + "    }\n"
                + "    dialog.value = false\n"
                + "    emit('initPage')\n"
                + "  }).finally(() => {\n"
                + "    loading.value = false\n"
                + "  })\n"
                + "}\n\n"
                + "function toForm(row?: " + model.className() + "View): " + model.className() + "CreateRequest & " + model.className() + "UpdateRequest {\n"
                + RenderSupport.renderTsToForm(model)
                + "}\n"
                + "</script>\n";
    }
}
