export const PERMISSIONS = {
  DASHBOARD_PAGE: 'upms:dashboard:page',
  DASHBOARD_GET: 'upms:dashboard:get',

  SYSUSER_PAGE: 'upms:sysuser:page',
  SYSUSER_GET: 'upms:sysuser:get',
  SYSUSER_ADD: 'upms:sysuser:add',
  SYSUSER_EDIT: 'upms:sysuser:edit',
  SYSUSER_DEL: 'upms:sysuser:del',

  SYSROLE_PAGE: 'upms:sysrole:page',
  SYSROLE_GET: 'upms:sysrole:get',
  SYSROLE_ADD: 'upms:sysrole:add',
  SYSROLE_EDIT: 'upms:sysrole:edit',
  SYSROLE_DEL: 'upms:sysrole:del',

  SYSDEPT_PAGE: 'upms:sysdept:page',
  SYSDEPT_GET: 'upms:sysdept:get',
  SYSDEPT_ADD: 'upms:sysdept:add',
  SYSDEPT_EDIT: 'upms:sysdept:edit',
  SYSDEPT_DEL: 'upms:sysdept:del',

  SYSTENANT_PAGE: 'upms:systenant:page',
  SYSTENANT_GET: 'upms:systenant:get',
  SYSTENANT_ADD: 'upms:systenant:add',
  SYSTENANT_EDIT: 'upms:systenant:edit',
  SYSTENANT_DEL: 'upms:systenant:del',

  TENANT_CATALOG_PAGE: 'upms:tenantcatalog:page',
  TENANT_CATALOG_GET: 'upms:tenantcatalog:get',
  TENANT_CATALOG_ADD: 'upms:tenantcatalog:add',
  TENANT_CATALOG_EDIT: 'upms:tenantcatalog:edit',
  TENANT_CATALOG_DEL: 'upms:tenantcatalog:del',

  SYSTEM_PAGE: 'upms:system:page',
  SYSTEM_GET: 'upms:system:get',

  SYSDICT_PAGE: 'upms:sysdict:page',
  SYSDICT_GET: 'upms:sysdict:get',
  SYSDICT_ADD: 'upms:sysdict:add',
  SYSDICT_EDIT: 'upms:sysdict:edit',
  SYSDICT_DEL: 'upms:sysdict:del',

  SYSCONFIG_PAGE: 'upms:sysconfig:page',
  SYSCONFIG_GET: 'upms:sysconfig:get',
  SYSCONFIG_ADD: 'upms:sysconfig:add',
  SYSCONFIG_EDIT: 'upms:sysconfig:edit',
  SYSCONFIG_DEL: 'upms:sysconfig:del',

  SYSCATEGORY_PAGE: 'upms:syscategory:page',
  SYSCATEGORY_GET: 'upms:syscategory:get',
  SYSCATEGORY_ADD: 'upms:syscategory:add',
  SYSCATEGORY_EDIT: 'upms:syscategory:edit',
  SYSCATEGORY_DEL: 'upms:syscategory:del',

  SYSMAIL_PAGE: 'upms:sysmail:page',
  SYSMAIL_GET: 'upms:sysmail:get',
  SYSMAIL_ADD: 'upms:sysmail:add',
  SYSMAIL_EDIT: 'upms:sysmail:edit',
  SYSMAIL_DEL: 'upms:sysmail:del',

  SYSNOTICE_PAGE: 'upms:sysnotice:page',
  SYSNOTICE_GET: 'upms:sysnotice:get',
  SYSNOTICE_ADD: 'upms:sysnotice:add',
  SYSNOTICE_EDIT: 'upms:sysnotice:edit',
  SYSNOTICE_DEL: 'upms:sysnotice:del',

  SECURITY_GET: 'upms:security:get',
  SECURITY_EDIT: 'upms:security:edit',

  AUDIT_PAGE: 'upms:audit:page',
  AUDIT_GET: 'upms:audit:get',
  AUDIT_EXPORT: 'upms:audit:export',
  AUDIT_DOWNLOAD: 'upms:audit:download',
  AUDIT_EDIT: 'upms:audit:edit',
  AUDIT_DEL: 'upms:audit:del',

  OPERATION_LOG_PAGE: 'upms:operationlog:page',
  OPERATION_LOG_GET: 'upms:operationlog:get',
  OPERATION_LOG_EXPORT: 'upms:operationlog:export',

  FILE_PAGE: 'upms:file:page',
  FILE_GET: 'upms:file:get',
  FILE_ADD: 'upms:file:add',
  FILE_DEL: 'upms:file:del',

  WORKFLOW_DESIGNER_PAGE: 'upms:workflowdesigner:page',
  WORKFLOW_DEFINITION_PAGE: 'upms:workflowdefinition:page',
  WORKFLOW_DEFINITION_GET: 'upms:workflowdefinition:get',
  WORKFLOW_DEFINITION_ADD: 'upms:workflowdefinition:add',
  WORKFLOW_DEFINITION_EDIT: 'upms:workflowdefinition:edit',
  WORKFLOW_DEFINITION_DEPLOY: 'upms:workflowdefinition:deploy',
  WORKFLOW_INSTANCE_PAGE: 'upms:workflowinstance:page',
  WORKFLOW_INSTANCE_GET: 'upms:workflowinstance:get',
  WORKFLOW_INSTANCE_ADD: 'upms:workflowinstance:add',
  WORKFLOW_INSTANCE_EDIT: 'upms:workflowinstance:edit',
  WORKFLOW_INSTANCE_DEL: 'upms:workflowinstance:del',
  WORKFLOW_TODO_PAGE: 'upms:workflowtodo:page',
  WORKFLOW_TODO_GET: 'upms:workflowtodo:get',
  WORKFLOW_TODO_EDIT: 'upms:workflowtodo:edit',
  WORKFLOW_DONE_PAGE: 'upms:workflowdone:page',
  WORKFLOW_DONE_GET: 'upms:workflowdone:get',

  CODEGEN_PAGE: 'upms:codegen:page',
  CODEGEN_GET: 'upms:codegen:get',
  CODEGEN_ADD: 'upms:codegen:add',
  CODEGEN_EDIT: 'upms:codegen:edit',
  CODEGEN_DEL: 'upms:codegen:del',
  CODEGEN_DOWNLOAD: 'upms:codegen:download',

  SYSMENU_PAGE: 'upms:sysmenu:page',
  SYSMENU_GET: 'upms:sysmenu:get',
  SYSMENU_ADD: 'upms:sysmenu:add',
  SYSMENU_EDIT: 'upms:sysmenu:edit',
  SYSMENU_DEL: 'upms:sysmenu:del',

  SESSION_PAGE: 'upms:session:page',
  SESSION_GET: 'upms:session:get',
  SESSION_KICK: 'upms:session:kick',
} as const

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS]

export const PERMISSION_CATALOG: Array<{
  code: PermissionCode
  label: string
  module: string
}> = [
  { code: PERMISSIONS.DASHBOARD_PAGE, label: '运行总览列表', module: 'dashboard' },
  { code: PERMISSIONS.DASHBOARD_GET, label: '运行总览查询', module: 'dashboard' },
  { code: PERMISSIONS.SYSUSER_PAGE, label: '用户管理列表', module: 'sysuser' },
  { code: PERMISSIONS.SYSUSER_GET, label: '用户管理查询', module: 'sysuser' },
  { code: PERMISSIONS.SYSUSER_ADD, label: '用户管理新增', module: 'sysuser' },
  { code: PERMISSIONS.SYSUSER_EDIT, label: '用户管理修改', module: 'sysuser' },
  { code: PERMISSIONS.SYSUSER_DEL, label: '用户管理删除', module: 'sysuser' },
  { code: PERMISSIONS.SYSROLE_PAGE, label: '角色管理列表', module: 'sysrole' },
  { code: PERMISSIONS.SYSROLE_GET, label: '角色管理查询', module: 'sysrole' },
  { code: PERMISSIONS.SYSROLE_ADD, label: '角色管理新增', module: 'sysrole' },
  { code: PERMISSIONS.SYSROLE_EDIT, label: '角色管理修改', module: 'sysrole' },
  { code: PERMISSIONS.SYSROLE_DEL, label: '角色管理删除', module: 'sysrole' },
  { code: PERMISSIONS.SYSDEPT_PAGE, label: '部门管理列表', module: 'sysdept' },
  { code: PERMISSIONS.SYSDEPT_GET, label: '部门管理查询', module: 'sysdept' },
  { code: PERMISSIONS.SYSDEPT_ADD, label: '部门管理新增', module: 'sysdept' },
  { code: PERMISSIONS.SYSDEPT_EDIT, label: '部门管理修改', module: 'sysdept' },
  { code: PERMISSIONS.SYSDEPT_DEL, label: '部门管理删除', module: 'sysdept' },
  { code: PERMISSIONS.SYSTENANT_PAGE, label: '租户管理列表', module: 'systenant' },
  { code: PERMISSIONS.SYSTENANT_GET, label: '租户管理查询', module: 'systenant' },
  { code: PERMISSIONS.SYSTENANT_ADD, label: '租户管理新增', module: 'systenant' },
  { code: PERMISSIONS.SYSTENANT_EDIT, label: '租户管理修改', module: 'systenant' },
  { code: PERMISSIONS.SYSTENANT_DEL, label: '租户管理删除', module: 'systenant' },
  { code: PERMISSIONS.TENANT_CATALOG_PAGE, label: '租户套餐列表', module: 'tenantcatalog' },
  { code: PERMISSIONS.TENANT_CATALOG_GET, label: '租户套餐查询', module: 'tenantcatalog' },
  { code: PERMISSIONS.TENANT_CATALOG_ADD, label: '租户套餐新增', module: 'tenantcatalog' },
  { code: PERMISSIONS.TENANT_CATALOG_EDIT, label: '租户套餐修改', module: 'tenantcatalog' },
  { code: PERMISSIONS.TENANT_CATALOG_DEL, label: '租户套餐删除', module: 'tenantcatalog' },
  { code: PERMISSIONS.SYSTEM_PAGE, label: '系统设置列表', module: 'system' },
  { code: PERMISSIONS.SYSTEM_GET, label: '系统设置查询', module: 'system' },
  { code: PERMISSIONS.SYSDICT_PAGE, label: '字典管理列表', module: 'sysdict' },
  { code: PERMISSIONS.SYSDICT_GET, label: '字典管理查询', module: 'sysdict' },
  { code: PERMISSIONS.SYSDICT_ADD, label: '字典管理新增', module: 'sysdict' },
  { code: PERMISSIONS.SYSDICT_EDIT, label: '字典管理修改', module: 'sysdict' },
  { code: PERMISSIONS.SYSDICT_DEL, label: '字典管理删除', module: 'sysdict' },
  { code: PERMISSIONS.SYSCONFIG_PAGE, label: '系统参数列表', module: 'sysconfig' },
  { code: PERMISSIONS.SYSCONFIG_GET, label: '系统参数查询', module: 'sysconfig' },
  { code: PERMISSIONS.SYSCONFIG_ADD, label: '系统参数新增', module: 'sysconfig' },
  { code: PERMISSIONS.SYSCONFIG_EDIT, label: '系统参数修改', module: 'sysconfig' },
  { code: PERMISSIONS.SYSCONFIG_DEL, label: '系统参数删除', module: 'sysconfig' },
  { code: PERMISSIONS.SYSCATEGORY_PAGE, label: '分类配置列表', module: 'syscategory' },
  { code: PERMISSIONS.SYSCATEGORY_GET, label: '分类配置查询', module: 'syscategory' },
  { code: PERMISSIONS.SYSCATEGORY_ADD, label: '分类配置新增', module: 'syscategory' },
  { code: PERMISSIONS.SYSCATEGORY_EDIT, label: '分类配置修改', module: 'syscategory' },
  { code: PERMISSIONS.SYSCATEGORY_DEL, label: '分类配置删除', module: 'syscategory' },
  { code: PERMISSIONS.SYSMAIL_PAGE, label: '邮件配置列表', module: 'sysmail' },
  { code: PERMISSIONS.SYSMAIL_GET, label: '邮件配置查询', module: 'sysmail' },
  { code: PERMISSIONS.SYSMAIL_ADD, label: '邮件配置新增', module: 'sysmail' },
  { code: PERMISSIONS.SYSMAIL_EDIT, label: '邮件配置修改', module: 'sysmail' },
  { code: PERMISSIONS.SYSMAIL_DEL, label: '邮件配置删除', module: 'sysmail' },
  { code: PERMISSIONS.SYSNOTICE_PAGE, label: '公告管理列表', module: 'sysnotice' },
  { code: PERMISSIONS.SYSNOTICE_GET, label: '公告管理查询', module: 'sysnotice' },
  { code: PERMISSIONS.SYSNOTICE_ADD, label: '公告管理新增', module: 'sysnotice' },
  { code: PERMISSIONS.SYSNOTICE_EDIT, label: '公告管理修改', module: 'sysnotice' },
  { code: PERMISSIONS.SYSNOTICE_DEL, label: '公告管理删除', module: 'sysnotice' },
  { code: PERMISSIONS.SECURITY_GET, label: '安全策略查询', module: 'security' },
  { code: PERMISSIONS.SECURITY_EDIT, label: '安全策略修改', module: 'security' },
  { code: PERMISSIONS.AUDIT_PAGE, label: '安全审计列表', module: 'audit' },
  { code: PERMISSIONS.AUDIT_GET, label: '安全审计查询', module: 'audit' },
  { code: PERMISSIONS.AUDIT_EXPORT, label: '安全审计导出', module: 'audit' },
  { code: PERMISSIONS.AUDIT_DOWNLOAD, label: '安全审计下载', module: 'audit' },
  { code: PERMISSIONS.AUDIT_EDIT, label: '安全审计治理', module: 'audit' },
  { code: PERMISSIONS.AUDIT_DEL, label: '安全审计删除', module: 'audit' },
  { code: PERMISSIONS.OPERATION_LOG_PAGE, label: '操作日志列表', module: 'operationlog' },
  { code: PERMISSIONS.OPERATION_LOG_GET, label: '操作日志查询', module: 'operationlog' },
  { code: PERMISSIONS.OPERATION_LOG_EXPORT, label: '操作日志导出', module: 'operationlog' },
  { code: PERMISSIONS.FILE_PAGE, label: '文件管理列表', module: 'file' },
  { code: PERMISSIONS.FILE_GET, label: '文件管理查询', module: 'file' },
  { code: PERMISSIONS.FILE_ADD, label: '文件管理上传', module: 'file' },
  { code: PERMISSIONS.FILE_DEL, label: '文件管理删除', module: 'file' },
  { code: PERMISSIONS.WORKFLOW_DESIGNER_PAGE, label: '流程设计器入口', module: 'workflowdesigner' },
  { code: PERMISSIONS.WORKFLOW_DEFINITION_PAGE, label: '流程定义列表', module: 'workflowdefinition' },
  { code: PERMISSIONS.WORKFLOW_DEFINITION_GET, label: '流程定义查询', module: 'workflowdefinition' },
  { code: PERMISSIONS.WORKFLOW_DEFINITION_ADD, label: '流程定义新增', module: 'workflowdefinition' },
  { code: PERMISSIONS.WORKFLOW_DEFINITION_EDIT, label: '流程定义修改', module: 'workflowdefinition' },
  { code: PERMISSIONS.WORKFLOW_DEFINITION_DEPLOY, label: '流程定义部署', module: 'workflowdefinition' },
  { code: PERMISSIONS.WORKFLOW_INSTANCE_PAGE, label: '流程实例列表', module: 'workflowinstance' },
  { code: PERMISSIONS.WORKFLOW_INSTANCE_GET, label: '流程实例查询', module: 'workflowinstance' },
  { code: PERMISSIONS.WORKFLOW_INSTANCE_ADD, label: '流程实例发起', module: 'workflowinstance' },
  { code: PERMISSIONS.WORKFLOW_INSTANCE_EDIT, label: '流程实例处理', module: 'workflowinstance' },
  { code: PERMISSIONS.WORKFLOW_INSTANCE_DEL, label: '流程实例终止', module: 'workflowinstance' },
  { code: PERMISSIONS.WORKFLOW_TODO_PAGE, label: '我的待办列表', module: 'workflowtodo' },
  { code: PERMISSIONS.WORKFLOW_TODO_GET, label: '我的待办查询', module: 'workflowtodo' },
  { code: PERMISSIONS.WORKFLOW_TODO_EDIT, label: '我的待办处理', module: 'workflowtodo' },
  { code: PERMISSIONS.WORKFLOW_DONE_PAGE, label: '我的已办列表', module: 'workflowdone' },
  { code: PERMISSIONS.WORKFLOW_DONE_GET, label: '我的已办查询', module: 'workflowdone' },
  { code: PERMISSIONS.CODEGEN_PAGE, label: '代码生成列表', module: 'codegen' },
  { code: PERMISSIONS.CODEGEN_GET, label: '代码生成查询', module: 'codegen' },
  { code: PERMISSIONS.CODEGEN_ADD, label: '代码生成新增', module: 'codegen' },
  { code: PERMISSIONS.CODEGEN_EDIT, label: '代码生成修改', module: 'codegen' },
  { code: PERMISSIONS.CODEGEN_DEL, label: '代码生成删除', module: 'codegen' },
  { code: PERMISSIONS.CODEGEN_DOWNLOAD, label: '代码生成下载', module: 'codegen' },
  { code: PERMISSIONS.SYSMENU_PAGE, label: '菜单管理列表', module: 'sysmenu' },
  { code: PERMISSIONS.SYSMENU_GET, label: '菜单管理查询', module: 'sysmenu' },
  { code: PERMISSIONS.SYSMENU_ADD, label: '菜单管理新增', module: 'sysmenu' },
  { code: PERMISSIONS.SYSMENU_EDIT, label: '菜单管理修改', module: 'sysmenu' },
  { code: PERMISSIONS.SYSMENU_DEL, label: '菜单管理删除', module: 'sysmenu' },
  { code: PERMISSIONS.SESSION_PAGE, label: '在线用户列表', module: 'session' },
  { code: PERMISSIONS.SESSION_GET, label: '在线用户查询', module: 'session' },
  { code: PERMISSIONS.SESSION_KICK, label: '在线用户强制下线', module: 'session' },
]

export const ALL_PERMISSIONS = PERMISSION_CATALOG.map((item) => item.code)