CREATE TABLE `codegen_template` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `tenant_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '所属租户',
  `name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '模板名称',
  `language` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '语言：java/typescript/vue',
  `path_pattern` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '匹配生成路径的正则或关键字',
  `content` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '模板内容（{{className}} 等占位）',
  `description` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '描述',
  `builtin` tinyint NOT NULL DEFAULT 0 COMMENT '是否内置（不可删除）',
  `created_by` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '更新人',
  `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除标记',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_codegen_template_tenant_name` (`tenant_id` ASC, `name` ASC) USING BTREE,
  INDEX `idx_codegen_template_tenant_lang_pattern` (`tenant_id` ASC, `language` ASC, `path_pattern` ASC) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '代码生成自定义模板' ROW_FORMAT = DYNAMIC;

INSERT INTO `codegen_template` (`tenant_id`, `name`, `language`, `path_pattern`, `content`, `description`, `builtin`, `created_by`, `updated_by`, `deleted`, `created_at`, `updated_at`)
SELECT 'platform', 'controller-head', 'java', 'Controller.java', '/* Generated by {{moduleName}} at {{generatedAt}} */\n', '生成器头部信息，可被所有 Controller 文件复用', 1, 'system', 'system', 0, NOW(), NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM `codegen_template` t WHERE t.tenant_id = 'platform' AND t.name = 'controller-head' AND t.deleted = 0
);