CREATE TABLE IF NOT EXISTS `sys_tenant_capability_resource_scope` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `tenant_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'platform' COMMENT '所属租户，当前固定为 platform',
  `capability_code` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '能力编码',
  `resource_key` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '资源键',
  `scope_type` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'VISIBLE' COMMENT '范围类型：VISIBLE 控制菜单可见，GRANT 控制授权建议',
  `required` tinyint NOT NULL DEFAULT 0 COMMENT '是否为能力基础资源',
  `created_by` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT 'system' COMMENT '创建人',
  `updated_by` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT 'system' COMMENT '更新人',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_tenant_capability_resource_scope` (`tenant_id` ASC, `capability_code` ASC, `resource_key` ASC, `scope_type` ASC) USING BTREE,
  INDEX `idx_capability_resource_scope_resource` (`tenant_id` ASC, `resource_key` ASC) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '租户能力资源范围表' ROW_FORMAT = DYNAMIC;

INSERT INTO `sys_tenant_capability` (`tenant_id`, `capability_code`, `capability_name`, `capability_desc`, `sort_order`, `enabled`, `created_by`, `updated_by`, `deleted`)
VALUES
  ('platform', 'file', '文件存储', '文件上传、预览与存储治理能力', 90, 1, 'system', 'system', 0),
  ('platform', 'workflow', '工作流', '流程定义、待办、已办与流程设计能力', 100, 1, 'system', 'system', 0),
  ('platform', 'codegen', '代码生成', '代码生成、下载与生成模块治理能力', 110, 1, 'system', 'system', 0)
ON DUPLICATE KEY UPDATE
  `capability_name` = VALUES(`capability_name`),
  `capability_desc` = VALUES(`capability_desc`),
  `sort_order` = VALUES(`sort_order`),
  `enabled` = VALUES(`enabled`),
  `updated_by` = VALUES(`updated_by`),
  `deleted` = VALUES(`deleted`),
  `updated_at` = NOW();

INSERT INTO `sys_tenant_capability_resource_scope` (`tenant_id`, `capability_code`, `resource_key`, `scope_type`, `required`, `created_by`, `updated_by`)
VALUES
  ('platform', 'auth', 'dashboard', 'VISIBLE', 1, 'system', 'system'),
  ('platform', 'auth', 'dashboard:read', 'GRANT', 1, 'system', 'system'),
  ('platform', 'auth', 'auth:read', 'GRANT', 1, 'system', 'system'),
  ('platform', 'user', 'system', 'VISIBLE', 1, 'system', 'system'),
  ('platform', 'user', 'users', 'VISIBLE', 1, 'system', 'system'),
  ('platform', 'user', 'user:read', 'GRANT', 1, 'system', 'system'),
  ('platform', 'user', 'user:write', 'GRANT', 1, 'system', 'system'),
  ('platform', 'role', 'system', 'VISIBLE', 1, 'system', 'system'),
  ('platform', 'role', 'roles', 'VISIBLE', 1, 'system', 'system'),
  ('platform', 'role', 'menus', 'VISIBLE', 1, 'system', 'system'),
  ('platform', 'role', 'role:read', 'GRANT', 1, 'system', 'system'),
  ('platform', 'role', 'role:write', 'GRANT', 1, 'system', 'system'),
  ('platform', 'role', 'system:read', 'GRANT', 0, 'system', 'system'),
  ('platform', 'role', 'system:write', 'GRANT', 0, 'system', 'system'),
  ('platform', 'dept', 'system', 'VISIBLE', 1, 'system', 'system'),
  ('platform', 'dept', 'depts', 'VISIBLE', 1, 'system', 'system'),
  ('platform', 'dept', 'dept:read', 'GRANT', 1, 'system', 'system'),
  ('platform', 'dept', 'dept:write', 'GRANT', 1, 'system', 'system'),
  ('platform', 'tenant', 'platform-management', 'VISIBLE', 1, 'system', 'system'),
  ('platform', 'tenant', 'tenants', 'VISIBLE', 1, 'system', 'system'),
  ('platform', 'tenant', 'tenant-catalog', 'VISIBLE', 1, 'system', 'system'),
  ('platform', 'tenant', 'tenant:read', 'GRANT', 1, 'system', 'system'),
  ('platform', 'tenant', 'tenant:write', 'GRANT', 1, 'system', 'system'),
  ('platform', 'system', 'system', 'VISIBLE', 1, 'system', 'system'),
  ('platform', 'system', 'settings', 'VISIBLE', 0, 'system', 'system'),
  ('platform', 'system', 'online-users', 'VISIBLE', 0, 'system', 'system'),
  ('platform', 'system', 'dicts', 'VISIBLE', 0, 'system', 'system'),
  ('platform', 'system', 'configs', 'VISIBLE', 0, 'system', 'system'),
  ('platform', 'system', 'mail-channel', 'VISIBLE', 0, 'system', 'system'),
  ('platform', 'system', 'categories', 'VISIBLE', 0, 'system', 'system'),
  ('platform', 'system', 'system:read', 'GRANT', 1, 'system', 'system'),
  ('platform', 'system', 'system:write', 'GRANT', 1, 'system', 'system'),
  ('platform', 'system', 'session:write', 'GRANT', 0, 'system', 'system'),
  ('platform', 'audit', 'audit', 'VISIBLE', 1, 'system', 'system'),
  ('platform', 'audit', 'operation-logs', 'VISIBLE', 0, 'system', 'system'),
  ('platform', 'audit', 'audit:read', 'GRANT', 1, 'system', 'system'),
  ('platform', 'audit', 'audit:write', 'GRANT', 0, 'system', 'system'),
  ('platform', 'audit', 'operation-log:read', 'GRANT', 0, 'system', 'system'),
  ('platform', 'audit', 'operation-log:export', 'GRANT', 0, 'system', 'system'),
  ('platform', 'notice', 'platform-management', 'VISIBLE', 1, 'system', 'system'),
  ('platform', 'notice', 'notices', 'VISIBLE', 0, 'system', 'system'),
  ('platform', 'notice', 'system:read', 'GRANT', 0, 'system', 'system'),
  ('platform', 'file', 'platform-management', 'VISIBLE', 1, 'system', 'system'),
  ('platform', 'file', 'files', 'VISIBLE', 1, 'system', 'system'),
  ('platform', 'file', 'file:read', 'GRANT', 1, 'system', 'system'),
  ('platform', 'file', 'file:write', 'GRANT', 1, 'system', 'system'),
  ('platform', 'workflow', 'platform-management', 'VISIBLE', 1, 'system', 'system'),
  ('platform', 'workflow', 'workflow', 'VISIBLE', 1, 'system', 'system'),
  ('platform', 'workflow', 'workflow-definitions', 'VISIBLE', 0, 'system', 'system'),
  ('platform', 'workflow', 'workflow-my-instances', 'VISIBLE', 0, 'system', 'system'),
  ('platform', 'workflow', 'workflow-todo', 'VISIBLE', 0, 'system', 'system'),
  ('platform', 'workflow', 'workflow-done', 'VISIBLE', 0, 'system', 'system'),
  ('platform', 'workflow', 'workflow-designer', 'VISIBLE', 0, 'system', 'system'),
  ('platform', 'workflow', 'workflow:read', 'GRANT', 1, 'system', 'system'),
  ('platform', 'workflow', 'workflow:write', 'GRANT', 1, 'system', 'system'),
  ('platform', 'codegen', 'platform-management', 'VISIBLE', 1, 'system', 'system'),
  ('platform', 'codegen', 'codegen', 'VISIBLE', 1, 'system', 'system'),
  ('platform', 'codegen', 'codegen:read', 'GRANT', 1, 'system', 'system'),
  ('platform', 'codegen', 'codegen:write', 'GRANT', 1, 'system', 'system'),
  ('platform', 'codegen', 'codegen:download', 'GRANT', 1, 'system', 'system')
ON DUPLICATE KEY UPDATE
  `required` = VALUES(`required`),
  `updated_by` = VALUES(`updated_by`),
  `updated_at` = NOW();