UPDATE `codegen_template`
SET `content` = '/* Generated by {{moduleName}} at {{generatedAt}} */\n{{defaultContent}}',
    `description` = '生成器头部信息，并保留默认 Controller 内容',
    `updated_by` = 'system',
    `updated_at` = NOW()
WHERE `tenant_id` = 'platform'
  AND `name` = 'controller-head'
  AND `builtin` = 1
  AND `deleted` = 0;